// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCAnkMyaFUT2WK0toBqrqVnFyzuUTRt6DA',
    appId: '1:499655887258:web:8ea733953842e097e91223',
    messagingSenderId: '499655887258',
    projectId: 'blogproject-b371d',
    authDomain: 'blogproject-b371d.firebaseapp.com',
    storageBucket: 'blogproject-b371d.appspot.com',
    measurementId: 'G-C1YSXFGX4H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBu71r8QUAe_G6tU2Gt5fGMlVVAu2vb-n8',
    appId: '1:499655887258:android:514939137227e999e91223',
    messagingSenderId: '499655887258',
    projectId: 'blogproject-b371d',
    storageBucket: 'blogproject-b371d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC4dbXqdJ1NNlFewV9_gJgS4NkagbYbXEk',
    appId: '1:499655887258:ios:8093339175df6d39e91223',
    messagingSenderId: '499655887258',
    projectId: 'blogproject-b371d',
    storageBucket: 'blogproject-b371d.appspot.com',
    iosClientId: '499655887258-kqvp55anpil2kpta6js3j1s2ejtiksoc.apps.googleusercontent.com',
    iosBundleId: 'com.example.blogproject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC4dbXqdJ1NNlFewV9_gJgS4NkagbYbXEk',
    appId: '1:499655887258:ios:8093339175df6d39e91223',
    messagingSenderId: '499655887258',
    projectId: 'blogproject-b371d',
    storageBucket: 'blogproject-b371d.appspot.com',
    iosClientId: '499655887258-kqvp55anpil2kpta6js3j1s2ejtiksoc.apps.googleusercontent.com',
    iosBundleId: 'com.example.blogproject',
  );
}
